Test how Try action handles jumping out of the blocks
outside: test
outside: test2
